### PR TITLE
fix: stop relations being all User[] if related model starts with User*

### PR DESCRIPTION
**Pull request by pierpo**

### CODE REVIEW

**Comment by mancku** [comment]
Hi @pierpo thanks for your help!
I did a couple of tests and found that didn't work 100% but you pointed me about the error and I think I could find a robust solution.

**Comment by pierpo** [comment]
Cool. This PR fixed it in my case but there has to be a better way indeed 😁 
Thanks!

**Comment by mancku** [comment]
Hi @pierpo I just published version 1.2.0 including this fix

**Comment by TimFoerster** [comment]
This change breaks following relation:
```
    "assignee": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "admin::user"
    }
```

Error Log:
```
at PostV414InterfaceBuilder.buildInterfaceText (node_modules\strapi-plugin-schemas-to-ts\dist\server\schemas-to-ts\interface-builders\interfaceBuilder.js:246:55)     
```

https://github.com/mancku/strapi-plugin-schemas-to-ts/blob/4ba0d2ae4286ad7b3ce43ed29db615ab6dea4a2c/server/schemas-to-ts/interface-builders/interfaceBuilder.ts#L287-L289
`attributeValue.target.split('.')[1]` resolvs in undefined.
Crashing the whole process.

**Pull request merged**
