### PR TITLE
Update interfaceBuilder.ts to fix #28

### LINKED ISSUE #28: strapi 4.14 - change source folder
Latest strapi version has change files location

>src/common/schemas-to-ts/BeforeRunEvent.ts:3:23 - error TS2307: Cannot find module '@strapi/database/**lib**/lifecycles/index' or its corresponding type declarations.

import { Event } from '@strapi/database/**dist**/lifecycles/index';

### PR DESCRIPTION
**Pull request by creazy231**
Fix #28
**Breaking change** for Strapi versions **< 4.14.x**

### CODE REVIEW

**Comment by creazy231** [comment]
This change leads to
```
strapi:dev: [strapi] src/common/schemas-to-ts/BeforeRunEvent.ts:5:22 - error TS2430: Interface 'BeforeRunEvent<TState>' incorrectly extends interface 'Event'.
strapi:dev: [strapi]   Types of property 'state' are incompatible.
strapi:dev: [strapi]     Type 'TState' is not assignable to type 'Record<string, unknown>'.
strapi:dev: [strapi] 
strapi:dev: [strapi] 5     export interface BeforeRunEvent<TState> extends Event {
strapi:dev: [strapi]                        ~~~~~~~~~~~~~~
strapi:dev: [strapi] 
strapi:dev: [strapi]   src/common/schemas-to-ts/BeforeRunEvent.ts:5:37
strapi:dev: [strapi]     5     export interface BeforeRunEvent<TState> extends Event {
strapi:dev: [strapi]                                           ~~~~~~
strapi:dev: [strapi]     This type parameter might need an `extends Record<string, unknown>` constraint.
strapi:dev: [strapi] 
strapi:dev: [strapi] Found 1 error(s).
```

Unfortunately don't have time to take a deeper look.

**Comment by 20x-dz** [comment]
@mancku or @SeedyROM Any chance to get this merged and released (probably as a new major version)?

**Comment by SeedyROM** [comment]
@20x-dz I unfortunately don't have write access to this repository. And ended up not using strapi for the project I was working on, so I haven't added any other ideas or features in a while.

**Comment by creazy231** [comment]
@SeedyROM may I ask you what else you used instead of strapi for your project?

**Comment by chestongo** [comment]
I need this to be merged :)

**Comment by creazy231** [comment]
Until this is merged, you can use `patch-package` (https://github.com/ds300/patch-package) or pnpm

**Comment by ktyumisc** [comment]
On v4.15, running into the same error and this fix resolves it. We need this merged!

**Comment by mancku** [comment]
Hi @creazy231 thanks for this PR! I've been kind of away for some weeks and haven't worked with the new Strapi versions. As I understand, this fixes a typing-related breaking change in the 4.15 version of Strapi, but does this fix affect people working with this plugin in previous versions of Strapi?

**Comment by creazy231** [comment]
Hey @mancku, since the paths are getting replaced with newer ones ( https://github.com/mancku/strapi-plugin-schemas-to-ts/pull/29/files#diff-3be62744427299fcc4db94afa5fd04b216e31922ba328f9e2cb6fed4de3a38a1L147 ) I think this will break Strapi versions < 4.14.x

**Comment by mancku** [comment]
Thanks @creazy231 I saw that but forgot to edit my reply, sorry 😅
Now, I'm working on it to return your version of the implementation only when the Strapi version is >= 4.14.x. I think that might work well and quick to solve the problem while maintaining compatibility. Hope to have it ready to test today

**Comment by mancku** [comment]
Hi @creazy231, @ktyumisc, @chestongo & @20x-dz 

I updated this PR to make @creazy231 work only when the version is > 4.14.x. 
I also pushed a new branch in the [Test Project](https://github.com/mancku/test-strapi-plugin-schemas-to-ts) so the plugin can be tested with both the 4.4 and the 4.14 versions.

I run some tests and it looks good, but having someone else check that it's working would be great, so I'd appreciate if some of you can also do it and give my some feedback before merging the PR and uploading a new version of the plugin.

Thanks!

**Comment by markok0stic** [comment]
Hi @mancku i have encountered the same error on strapi v4.15.4 (lts at the moment). I have injected the plugin from the [Test Project](https://github.com/mancku/test-strapi-plugin-schemas-to-ts), you mentioned, inside of my strapi project and those are the results:

image


- Everything seems the same (idk about version 4.14) but I used the plugin from your 4.14 test project.

**Comment by SeedyROM** [comment]
Sorry to interrupt the thread, but this is another reason I abandoned strapi, the incompatibility between minor version was something that's such nightmare to deal with constantly. It leads to you just not updating ever lol. The strapi devs don't seem to understand what major and minor version mean to end users lol.

**Comment by mancku** [comment]
@markok0stic you're either using a version of the plugin code different from the one on this PR, or Strapi configuration is not detecting your version, because that import belongs either to the old code or to the class called `PreV414InterfaceBuilder`.

@SeedyROM you nailed that one. It's saddening.

**Comment by markok0stic** [comment]
@mancku Could you provide me the version I need to re-test with, please?

**Comment by markok0stic** [comment]
@mancku Yeah, you were right but i thought that you already updated the plugin in the [Test Project](https://github.com/mancku/test-strapi-plugin-schemas-to-ts), mb.
Results after re-test:
image

- Everything seems fine, also tried to generate few interfaces so this worked for me!

**Comment by mancku** [comment]
@markok0stic no. That's part of the complexity of testing this plugin. I created that project, but the project works with the sub-module, so when you clone it, you're cloning the main version of the plugin. To test a different version, you have to work through GIT to se the one that you'd like to test, as I assume you did. 
Thanks for confirming that it works fine!

**Comment by markok0stic** [comment]
Yeah, fair enough!
Cool!
Happy to use it again after release.

**Comment by creazy231** [comment]
@SeedyROM using Strapi with official plugins is 99% of the time not a problem. But yea, maintaining plugins and packages sometimes is a mess because of breaking changes for plugin developers. Looking forward it's getting better with v5.

**Comment by 20x-dz** [comment]
@creazy231 That is basically the point: "breaking changes". That's by [semver](https://semver.org/) definition **THE** reason to increase the major version number. Why they stick to the 4 is beyond me since it can be used as a marketing naming convention just fine.

Their release history speaks for itself: [v4.15.1](https://github.com/strapi/strapi/releases/tag/v4.15.1), [v4.14.1](https://github.com/strapi/strapi/releases/tag/v4.14.1), [v4.13.1](https://github.com/strapi/strapi/releases/tag/v4.13.1), [v4.12.7](https://github.com/strapi/strapi/releases/tag/v4.12.7), [v4.11.6](https://github.com/strapi/strapi/releases/tag/v4.11.6), …
And these were just in the last 3-4 months…

@mancku Thank you for your work! 💪

**Comment by mancku** [comment]
Thanks @20x-dz !!

@creazy231 I look forward to the v5 too. Hope they fix the many mistakes made in the v4. IMO, honestly, this plugin should not be necessary at all, and I can't understand why they did the Typescript implementation the way they did it.

That said, I'm going to merge this PR and I'll try to release the new version of the plugin tomorrow

**Comment by 20x-dz** [comment]
@mancku I'm afraid that the released version wasn't build and published properly to npmjs, at least according to https://diff.intrinsic.com/strapi-plugin-schemas-to-ts/1.1.10/1.1.20 (and the build errors I get).

**Comment by mancku** [comment]
@20x-dz thanks for pointing it out! I don't even know how I did manage to publish with only the differences in the package.json and the changelog 🤯 anyway it's fixed now in the 1.1.21.
I didn't know that tool for comparing versions. It's great!

**Comment by 20x-dz** [comment]
Thx a ton for your quick update! After deleting the generated files from the previous version (1.1.10) it works like a charm now! 💪 

```
$ rm -rf src/common
$ rm -rf src/**/interfaces/*.ts
$ rm -rf src/api/**/content-types/**/*.ts
```

**Comment by mancku** [comment]
Happy to hear that @20x-dz !! BTW I'm trying to add a feature to be able to delete the files based on the comment they have in the first line. I suggested it in https://github.com/mancku/strapi-plugin-schemas-to-ts/issues/22#issue-1812883127 for a different feature, but I think it'd be great to be able to perform that delete from the terminal. Something like `strapi-plugin-schemas-to-ts --delete-generated-interfaces` . Maybe less verbose, tho 🤣

**Comment by 20x-dz** [comment]
True, that would come in very handy.

Otoh, if you build this functionality, it could just run before generating the types as well, couldn't it? 🤔

**Comment by markok0stic** [comment]
> Thx a ton for your quick update! After deleting the generated files from the previous version (1.1.10) it works like a charm now! 💪
> 
> ```shell
> $ rm -rf src/common
> $ rm -rf src/**/interfaces/*.ts
> $ rm -rf src/api/**/content-types/**/*.ts
> ```

@20x-dz 
This is going to delete all ts files inside the <content-type-name> dir and I would not recommend this since you can create lifecycles and all you want in there.

**Comment by 20x-dz** [comment]
@markok0stic fair point, I recover them through git. I'll add a note to my original comment.

**Comment by mancku** [comment]
Hi @20x-dz @markok0stic I just published version 1.2.0, which includes https://github.com/mancku/strapi-plugin-schemas-to-ts/pull/47, allowing for files to be deleted from within the plugin

**Pull request merged**
